#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

function handle_sig_term(){
   echo "I hate the kill command";
   rm "/var/run/myscript.pid";
}

function handle_sig_int(){
    echo 'Y U no love me?!";
}
function handle_sig_quit(){
    rm "/var/run/myscript.pid";

#Handle some signals
trap 'handle_sig_term' SIGTERM;
trap 'handle_sig_int' SIGINT;
trap 'handle_sig_quit' SIGQUIT;

echo $$ > "/var/run/myscript.pid";

#this will excute indefinetly unless interrupted 
while true; do
    echo "To infinity and beyond";
done
