#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM 

file=/var/run/holbertonscript.pid
function finishQuit {
    sudo rm $file
    exit
}
function finishTerm {
    echo 'I hate the kill command'
    sudo rm $file
    exit
}
trap finishTerm SIGTERM
trap finishQuit SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
sudo bash -c "echo $$ > $file"
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done

